# Generated by Django 5.2.6 on 2025-09-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='generated_cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='generated_resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
